### ISSUE TITLE
Support for Web Notifications

### ISSUE THREAD

**Issue by sampavlovic** [Jujuyeh/webapp-creator#33] opened 2017-11-05 01:21 UTC
Web Notification API is something essential for the experience and according to Mozilla's documentation it seems simple enough that I believe that it can be shimmed easily into QML

https://developer.mozilla.org/en-US/docs/Web/API/notification

There is also an example code for implementing catching the web api signal on Qt with this stackoverflow question

https://stackoverflow.com/questions/28824296/how-to-customize-notification-web-api-in-the-qt

Would it be possible to integrate something like this to the ogra container?

**Comment by Jujuyeh** [comment] 2017-11-05 10:23
If you find a way to make notifications work in simple webapps, it should do on ogra webapps too.

Here is the Ubuntu Web Notification API Docs: https://docs.ubuntu.com/phone/en/platform/guides/push-notifications-client-guide

So, for the push-notifications https://push.ubuntu.com/ is used.

Still, there's no way to ensure this to be useful in a long-term. We don't know what will happen with the Ubuntu One support. I believe UBports is working on this, and they pose as a solution to use no unified push service. We might rely on a background service and given this, all work made for the push-notification system might be done in vain.

For now, I'll close this issue and reopen it when a solution is given.

**Closed as completed by Jujuyeh** 2017-11-05 10:23 UTC

**Comment by mateosalta** [comment] 2017-11-08 23:43
hm, I'll look into it sometime, but the notifications should be coming from the website it self right?

**Comment by Jujuyeh** [comment] 2017-11-09 11:31
Yes, the problem is that Ubuntu Touch needs a new push-notification system. Then, we could look how the webapp could 'speak' to that.
